services:
    laravel-rest-api:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel-rest-api
        ports:
            - "8000:8000"
        volumes:
            - .:/var/www/html
        depends_on:
            - mongo-db
        networks:
            - open-food-network

    mongo-db:
        image: mongo:latest
        container_name: mongo-db
        ports:
            - "${MONGO_DB_PORT}:${MONGO_DB_PORT}"
        environment:
            MONGO_INITDB_ROOT_USERNAME: ${MONGO_DB_USERNAME}
            MONGO_INITDB_ROOT_PASSWORD: ${MONGO_DB_PASSWORD}
        volumes:
            - ./mongodata:/data/db
        networks:
            - open-food-network

    mongo-express:
        image: mongo-express
        container_name: mongo-express
        ports:
            - "8081:8081"
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_DB_USERNAME}
            ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_DB_PASSWORD}
            ME_CONFIG_MONGODB_SERVER: ${MONGO_DB_HOST}
        depends_on:
            - mongo-db
        networks:
            - open-food-network

networks:
    open-food-network:
        driver: bridge

